<?php
	require_once('controllers/AdminController.php');
	require_once('controllers/DepartmentsController.php');
	require_once('controllers/HomeController.php');
	require_once('controllers/ItemsController.php');
	require_once('controllers/ListsController.php');
	require_once('controllers/LuckyDipsController.php');
	require_once('controllers/OrdersController.php');
	require_once('controllers/PackSizesController.php');
