<?php
	require_once('models/DalResult.php');
	require_once('models/Department.php');
	require_once('models/Item.php');
	require_once('models/LuckyDip.php');
	require_once('models/Meal.php');
	require_once('models/MealItem.php');
	require_once('models/MealPlanDay.php');
	require_once('models/Order.php');
	require_once('models/OrderItem.php');
	require_once('models/PackSize.php');
	require_once('models/ShopList.php');
	require_once('models/Tag.php');
