CREATE TABLE `orders` ( `id` INT NOT NULL AUTO_INCREMENT , `date_ordered` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `order_items` ( `id` INT NOT NULL AUTO_INCREMENT , `order_id` INT NOT NULL , `item_id` INT NOT NULL , `quantity` INT NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `order_items` ADD FOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `order_items` ADD FOREIGN KEY (`item_id`) REFERENCES `items`(`item_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
